services:
  - type: web
    name: ronoos-backend
    plan: free
    rootDir: backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ronoos_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: CLOUDINARY_CLOUD_NAME
        value: "backend"
      - key: CLOUDINARY_API_KEY
        value: "885592763692399"
      - key: CLOUDINARY_API_SECRET
        value: "g1mdpTCjZDq0koX-gx1eKtyASvQ"
      - key: DATABASE_URL
        fromDatabase:
          name: ronoos-db
          property: connectionString

databases:
  - name: ronoos-db
    plan: free
    databaseName: ronoos_db
    user: ronoos_user
