services:
  - type: web
    name: ronoos-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ronoos_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        fromService:
          type: web
          name: ronoos-backend
          envVar: RENDER_EXTERNAL_HOSTNAME
      - key: DATABASE_URL
        fromDatabase:
          name: ronoos-db
          property: connectionString

databases:
  - name: ronoos-db
    databaseName: ronoos_db
    user: ronoos_user
